### ISSUE TITLE
Error install Nuget - macios

### ISSUE THREAD

**Issue by bcaceiro** [MPowerKit/Lottie#1]
Hi, I have a solution, only targeting iOS and Android, tried to install the package (in windows pc) and get the following error:

```
  NotFound https://pkgs.dev.azure.com/xamarin/6fd3d886-57a5-4e31-8db7-52a1b47c07a8/_packaging/42c1603f-3d61-4146-8020-ec5b7b392084/nuget/v3/flat2/mpowerkit.lottie.macios/index.json 387ms
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\bcaceiro\.nuget\packages\mpowerkit.lottie.macios\4.5.0\lib\net8.0-ios17.2\MPowerKit.Lottie.MaciOS.resources\LottieProxy-ios.xcframework\ios-arm64_x86_64-simulator\LottieProxy.framework\Modules\LottieProxy.swiftmodule\arm64-apple-ios-simulator.abi.json'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
```

the install fails because of macios .nukpg

**Comment by Alex-Dobrynin** [comment]
this is about long path on windows

here is how you can workaround this:
1. https://www.minitool.com/news/fix-destination-path-too-long.html
2. https://learn.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-long-path

Note: you need to activate first, then second.
After that from developer terminal in visual studio run ```dotnet add package MPowerKit.Lottie``` and ```dotnet restore```
After that you are able to manage and update your nugets from nuget browser in VS

This helped me on my PC

**Comment by npagare** [comment]
Hello @Alex-Dobrynin, I'm facing the same issue. I followed both steps as suggested by you. But it was not able to install the nuget package via Nuget management panel.
But, run following command at the package manager console - dotnet add package MPowerKit.Lottie --version 1.0.2 to add the package. 

Thank you for your help.

**Comment by bcaceiro** [comment]
Indeed, I also tried these steps and still facing the same issue. If it would be possible to rename some of the projects to have a smaller string would be great.
