### ISSUE TITLE
Properties for IsPlaying and Loop

### ISSUE THREAD

**Issue by npagare** [MPowerKit/Lottie#2]
Hello @Alex-Dobrynin ,

Which properties should be used to replace IsPlaying and Loop properties when converting from Xamaring.Form?

Thank you for your help.

**Comment by Alex-Dobrynin** [comment]
There are not such properties as IsPlaying and Loop, but please, read the doc, there are described how you can use start/stop/pause/resume. For looping there are such properties as RepeatMode and RepeatCount.
